dist: trusty
sudo: true
language: python3
rvm:
- 2.1
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get install -y librsvg2-bin imagemagick
  - sudo apt-get install python3-pip
  - sudo python3 -m pip install python-frontmatter commonmark
  - gem install ruby_dep -v 1.3.1
  - gem install listen -v 3.0.8
  - gem install jekyll
  - gem install jekyll-redirect-from
before_script:
  - cd bin
  - ./mkcard.sh
  - python3 frontmatter_update.py
  - python3 fm2tag.py
  - python3 mkamp.py
  - cd ..
script:
  - jekyll build --source www
branches:
  only:
  - gh-pages
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
  provider: s3
  access_key_id: AKIAJLZ4VZK3GII4HOYA
  secret_access_key:
    secure: WLbdklZak6WFUUXeVtBwM9KwHlhlqcxhIZBimhYLr0bTohCCmxgPRR2QoCf3Hey6SSKxBasJd+pyaPb9sjhhpXo/NIEvlbaamPm6bkj1ZErX/Ej4kIPJaA/wA0C7uQKJ0vBcj/dsTVHhRl0pikQ9XeU2gTs/H5M3/vcv/PRkMO7s/0M0Tas+vE+KcvWD7KgrE8H2hGH/1xB5I5iz92Qc3H3Jt7ccstfAG1mq5qQe5GSDDRZWwC2s9U56S6OVAiKcQVtDg/jBP3520ukR4xJZ3/gfag0NKAOen3WV5Wjh6WXlKESc8vWI6CLheI3oRyDT1l24QDcUwvRWFug/XVs0xIW9wwlZEE86gVTxRRgJLgSMYjySaznmkEb45L0pqymsDVzr7KeK2biLgPylog44gG+vzXO7wUaEOdI5YcsFWJHsYEfAf95JphyU6/aBVYXbexEa8nW5/0PatBmDQnXQwmZGNcDFzKuKf0wNvEdmca8Itg2saNaTErKpvMmXv1f1jCKI4WCpTM+/zpatSPYykxXxeQ/M93F/RU8zHmODi+SB49hUWzXAYpJGww7PkZy07FY1GrhLf6ROYFTYrNAEGTSy5LRkgrmJ1QVCJUfeXfxLD3PPqz3guwoQFkFIPHcwmssZeTu8Wy8C6I73pMMl58knGt3GIgNxV1JqE2oy61U=
  bucket: www.vectorlogo.zone
  local-dir: _site
  skip_cleanup: true
  on:
    repo: fileformat/vectorlogozone
    branch: gh-pages
