#
# _config.yml for HackerLogos
#

exclude: [ "*.sh", "**/*_src*" ]
production_url: https://www.vectorlogo.zone
title : Vector Logo Zone
title_short: VLZ
plugins:
  - jekyll-redirect-from
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
